= Photo Based Gallery Recomendations
:slug: 05-gdsaa-photo-based-gallery-recommendations
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:module-next-title: Summary: Applied Graph Data Science for Web Applications

video::DQ7fH0QUg6A[youtube,width=560,height=315]

_Similarity algorithms and Label Propagation overview_

In this section you will use the Label Propagation algorithm to recommend photos.

[NOTE]
====
.Useful Resources

* https://neo4j.com/docs/graph-data-science/current/algorithms/label-propagation/[Label Propagation^]
====

== Exercise

. In Neo4j Browser, perform the steps in the  Neo4j Browser guide section *Photo Recommendations*. (:play gds-applied-graph-algorithms-exercises/05_photo_recommendations.html)
. In CodeSandbox, edit the `FETCH_PHOTO_RECOMMENDATIONS` Cypher query in `src/exercises/exercise4.js` to recommend businesses whose photos belong to the same community.
. Save this file.
. In the CodeSandbox Browser, click *Photos* and select five random photos. Then the application presents restaurants based upon the photos selected.

== Solution

If you get stuck, watch this video for a walk-through of the solution:

++++
<div style="position: relative; overflow: hidden; padding-top: 56.25%; width: 90%;">
  <iframe src="https://www.youtube.com/embed/FV0LznTB364" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;" allowfullscreen></iframe>
</div>
++++
_Photo based recommendations solution_

[.quiz]
== Check your understanding
=== Question 1

=== Algorithm Understanding: LPA

[.statement]
Which category of algorithms best describes LPA?

[.statement]
Select the correct answer.

[%interactive.answers]
- [ ] Centrality
- [ ] Similarity & ML Workflow
- [x] Community Detection
- [ ] Pathfinding and Search

=== Question 2

=== Running the algorithm in Neo4j

[.statement]
Which voting mechanism does Neo4j's Label Propagation algorithm use?

[.statement]
Select the correct answer.

[%interactive.answers]
- [ ] Random Walk Method
- [x] Pull Method
- [ ] Push Method
- [ ] Modularity Optimization Method

[.summary]
== Summary

You should now be able to:
[square]
* Use the Jaccard similarity algorithm.
* Use the Label Propagation Community Detection algorithm with Neo4j.
