= Using a Machine Learning Workflow for Link Prediction
:slug: 00-gdsds-about-this-course
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:module-next-title: Setting Up your Development Environment
:page-slug: {slug}
:page-type: training-course-index
:page-pagination: next
:page-layout: training
:page-module-duration-minutes: 5

== About this course

This course introduces you to using Neo4j as part of your Data Science and Machine Learning workflows.
You will learn how to do this with the help of the https://aminer.org/citation[aminer.org citation dataset^].
This dataset contains papers, authors, and citations from DBLP - a computer science bibliography website.

This course is intended for data scientists and data analysts.

This self-paced training should take you four hours to complete if you perform all of the hands-on exercises in the course.

We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance.
You should register on the Neo4j Community site  where you can view other questions and answers for students taking our online training courses.
The _Neo4j Community Site_ is an excellent resource for answering many types of questions posed by other users of Neo4j.

There are four modules in this course.
Most modules have hands-on exercises you should complete and all modules have a set of review questions at the end.
If you answer all review questions correctly, you will receive a Certificate of Completion for this course.
The hands-on exercises in this course can be completed using Neo4j Desktop and Jupyter Notebook.
We have provided an estimate of how long each module should take you to complete if you perform the hands-on exercises.

== Setting Up Your Development Environment

[square]
* Set up your Neo4j development environment for performing the hands-on exercises of this course.
* Set up your Python environment for running Jupyter notebooks in this course.

Estimated time: _30 minutes_

== Exploratory Data Analysis

[square]
* Query a database for its schema.
* Return and chart the number of node labels and relationship types using matplotlib.
* Build and plot a histogram of papers and their citations using pandas and matplotlib.

Estimated time: _30 minutes_

== Recommendations

[square]
* Find potential collaborators for an author.
* Find relevant papers about a topic for an author.

Estimated time: _60 minutes_


== Predictions

[square]
* Describe what link prediction is.
* Use the link prediction graph algorithms in Neo4j.
* Understand the challenges when building Machine Learning models on graph data.
* Build a link prediction classifier using scikit-learn with features derived from the Neo4j Data Science Library

Estimated time: _90 minutes_



== Summary

[square]
* Download Certificate of Completion.
* Resources to learn more.
* Course feedback.
