= Summary: Using a Machine Learning Workflow for Link Prediction
:slug: 06-gdsds-summary
:doctype: book
:toc: left
:toclevels: 3
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-certificate:
:page-module-duration-minutes: 5

== Course Summary

In this course, you have learned how to:

[square]
* Set up your Neo4j development environment for performing the hands-on exercises of this course.
* Query a database for its schema.
* Return and chart the number of node labels and relationship types using matplotlib.
* Build and plot a histogram of papers and their citations using pandas and matplotlib.
* Build a mini recommendation engine with Cypher queries to:
    ** Find potential collaborators for an author.
    ** Find relevant papers about a topic for an author.
* Describe what Link Prediction is.
* Use the Link Prediction functions in Neo4j.
* Understand the challenges when building Machine Learning models on graph data.
* Build a Link Prediction classifier using scikit-learn with features derived from the Neo4j Graph Data Science library.

== Next steps

There are many resources available to you for learning more about doing Data Science with Neo4j.


* https://neo4j.com/graph-algorithms-book/[O'Reilly Graph Algorithms Book^]

* https://medium.com/neo4j/tagged/data-science[Neo4j Analytics Category on Medium^]

* https://tbgraph.wordpress.com/[Tomaz Bratanic’s Blog^]

* https://www.octavian.ai/[Octavian AI^]

== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/k6nhzMXiYFyUYUNs7[feedback] so we can improve this course.
