= Photo Based Gallery Recommendations
:slug: 05-photo-based-gallery-recommendations
:neo4j-version: 3.5
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-quiz:

video::Rf-dlMCKRlg[youtube]

_Similarity algorithms and Label Propagation overview_

In this section you will use the Label Propagation algorithm to recommend photos.

[NOTE]
====
.Useful Resources

* https://neo4j.com/docs/graph-algorithms/current/algorithms/label-propagation/[Label Propagation^]
====

== Exercise

. In Neo4j Browser, perform the steps in the  Neo4j Browser guide section *Photo Recommendations*. (:play applied_graph_algorithms/05_photo_recommendations.html)
. In CodeSandbox, edit the `FETCH_PHOTO_RECOMMENDATIONS` Cypher query in `src/exercises/exercise4.js` to recommend businesses whose photos belong to the same community.
. Save this file.
. In the CodeSandbox Browser, click *Photos* and select five random photos. Then the application presents restaurants based upon the photos selected.

== Solution

If you get stuck, watch this video for a walk-through of the solution:

video::FV0LznTB364[youtube]

_Photo based recommendations solution_

[.quiz]
== Check your understanding

=== Question 1

*Algorithm Understanding: LPA*

Which category of algorithms best describes LPA?

Select the correct answer.

[%interactive.answers]
- [ ] Centrality
- [ ] Similarity & ML Workflow
- [x] Community Detection
- [ ] Pathfinding and Search

=== Question 2

*Running the algorithm in Neo4j*

Which voting mechanism does Neo4j's Label Propagation algorithm use?

Select the correct answer.

[%interactive.answers]
- [ ] Random Walk Method
- [x] Pull Method
- [ ] Push Method
- [ ] Modularity Optimization Method

== Summary

You should now be able to:
[square]
* Use the Jaccard similarity algorithm.
* Use the Label Propagation Community Detection algorithm with Neo4j.
