= Importing Data with Neo4j 4.x: Summary
:slug: 07-import-40-summary
:doctype: book
:toc: left
:toclevels: 3
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-certificate:
:page-module-duration-minutes: 5

== Course Summary

In this course, you have learned how to:

[square]
* Describe the many ways you can import data with Neo4j.
* Use LOAD CSV to import data.
* Use APOC to import data
* Use the `neo4j-admin` tool to import data.
* Use an application to import data.
* Use the ETL Tool to import data.

== Resources

There are many resources available to you for learning more about Neo4j and Cypher.

https://neo4j.com/developer/resources/

Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users:

https://community.neo4j.com

Neo4j documentation:

https://neo4j.com/docs/


Neo4j Sandboxes for experimenting with graphs:

https://
sandbox.neo4j.com/?ref=graph-academy

Videos on  the Neo4j YouTube channel:

https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

Neo4j online and instructor-led training:

https://neo4j.com/graphacademy/

Become a Neo4j certified developer:

https://neo4j.com/graphacademy/neo4j-certification/

GitHub repository:

https://github.com/neo4j-contrib

Neo4j events all over the world:

https://neo4j.com/events/world/all/

Graph Gists for learning more use cases for Neo4j:

https://neo4j.com/graphgists/

Attend a Neo4j meetup:

https://www.meetup.com/topics/neo4j/

View questions/answers raised about Neo4j:

https://stackoverflow.com/tags/neo4j/hot


== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/k6nhzMXiYFyUYUNs7[feedback] so we can improve this course.

