= Overview of Neo4j 4.x
:slug: 00-overview40-about
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:module-next-title: Neo4j is a Graph Database
:page-slug: {slug}
:page-type: training-course-index
:page-pagination: next
:page-layout: training
:page-module-duration-minutes: 5

== About this course

ifndef::env-slides[]
This course introduces you to graph databases and how Neo4j supports them. You will learn about the features and components of the Neo4j Graph Platform.
endif::[]

This course is intended for developers, administrators, architects, data scientists, and data analysts.
You need not have programming experience to take this training.

ifndef::env-slides[]
In this course, you can complete hands-on guided exercises to get started using Neo4j.
You can complete the hands-on exercises in one of three ways, using:

[square]
[.statement]
* Neo4j Desktop
* Neo4j Sandbox
* Neo4j Aura
endif::[]

ifdef::backend-html5[]
At the end of each lesson are a set of questions that you must answer correctly to mark the lesson as completed.
If you complete all lessons, you will receive a _Certificate of Completion_.

If you perform the hands-on guided exercises, this course will take you approximately 2 hours to complete.
endif::[]

ifdef::env-slides[]
[square]
* Understand when to use  *graph databases*
* Learn about *Neo4j components*
* Do *hands-on exercises* working with Neo4j
endif::[]

This Course is published by Neo4j per this https://neo4j.com/docs/license/[License for Use^].

ifndef::env-slides[]
== Lesson Overview

Here are the lessons of this course:
endif::[]

ifdef::env-slides[]
[.half-column]
== Specific Areas of Study
endif::[]

[.small]
--
. Neo4j is a Graph Database
. The Neo4j Graph Platform
--
== Resources

ifndef::env-slides[]
We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance.
You should register on the community site where you can view other questions and answers for students taking our online training courses.
The Neo4j Community Site is an excellent resource for answering many types of questions posed by other users of Neo4j.

Here are some resources you will use as you learn about Neo4j and Cypher for this course:


[square]
* https://neo4j.com/docs/cypher-manual/4.0/[Neo4j Cypher Manual]
* https://neo4j.com/docs/cypher-refcard/current/[Neo4j Cypher Refcard]
* https://neo4j.com/docs/labs/apoc/current/[APOC Documentation]
* https://neo4j.com/docs/driver-manual/current/[Neo4j Drivers Manual]
* https://community.neo4j.com/c/general/online-training[Neo4j Community Site]
endif::[]

ifdef::env-slides[]
[square]
* Neo4j Cypher Manual   https://neo4j.com/docs/cypher-manual/4.0/
* Neo4j Cypher Refcard  https://neo4j.com/docs/cypher-refcard/current/
* APOC Documentation    https://neo4j.com/docs/labs/apoc/current/
* Neo4j Drivers Manual  https://neo4j.com/docs/driver-manual/current/
* Neo4j Community Site  https://community.neo4j.com/c/general/online-training

[.instructor-notes]
--
Here’s a list of some great Neo4j resources.

You’ll find a discussion area in the Neo4j Community Site.
[square]
* The Neo4j Community Site is an excellent resource for answering many types of questions posed by Neo4j users.
* I recommend that you should register on this community site.
* There  you can view other questions and answers.

As you work with Neo4j, when encountering problems and when questions arise, -

[square]
* search community site for answers and pose new questions.
--
endif::[]
