= Basic Neo4j 4.0 Administration
:slug: 00-basic-neo4j-admin-about
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:module-next-title: Introduction to Neo4j

== About this course

This course introduces you to graph databases and how perform basic administration tasks for an installation that supports a group of developers or an installation that is being deployed.
This course teaches tasks that are available in Neo4j 4.x Enterprise Edition.

[.notes]
--
This course is intended for developers, administrators, and architects.
You need not have programming experience to take this training.
--

In this course, you complete hands-on exercises to gain experience with Neo4j Administration.
You must use Docker installed on your system or in a cloud instance for the hands-on exercises.

ifdef::backend-html5[]
At the end of each lesson are a set of questions that you must answer correctly to mark the lesson as completed.
If you complete all lessons, you will receive a _Certificate of Completion_.

If you perform the hands-on exercises, this course will take you approximately 6-8 hours to complete.
endif::[]


This Course is published by Neo4j per this https://neo4j.com/docs/license/[License for Use^].

== Lesson Overview

ifndef::backend-revealjs[]
Here are the lessons of this course:
endif::[]

[.small]
. Introduction to Neo4j
. Overview of Neo4j Administration
. Managing a Neo4j Instance
. Using cypher-shell to Manage Databases
. Copying Databases
. Changing the Database Location
. Checking Database Consistency
. Scripting to Manage Databases
. Configuring Plugins
. Managing HTTP Ports
. Managing Backups
. Importing data


== Resources

ifndef::backend-revealjs[]
We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance.
You should register on the community site where you can view other questions and answers for students taking our online training courses.
The Neo4j Community Site is an excellent resource for answering many types of questions posed by other users of Neo4j.
endif::[]

Here are some resources you will use as you learn about Neo4j for this course:

[square]
* https://neo4j.com/docs/operations-manual/4.0/[Neo4j Operations Manual]
* https://neo4j.com/docs/cypher-manual/4.0/[Neo4j Cypher Manual]
* https://neo4j.com/docs/cypher-refcard/current/[Neo4j Cypher Refcard]
ifdef::backend-revealjs[]
* https://community.neo4j.com/c/general/online-training[Neo4j Community Site]
endif::[]
