
= Scripting to Manage Databases
:slug: 08-scripting-manage-databases
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:module-next-title: Configuring Plugins

////
ifdef::backend-html5[]

include::scripts.txt[]

endif::backend-html5[]
////

== About this module

In most cases, you will want to automate the management of a Neo4j instance.

At the end of this module, you should be able to:
[square]
* Create Cypher scripts to change a database.
* Create shell scripts to execute Cypher scripts.
* Create shell scripts to execute a set of shell scripts.

== Scripting with cypher-shell

As a database administrator, you may need to automate changes to databases.
The most common types of changes that administrators may want to perform are related to the application.
As an administrator, you work with architects and developers to created scripts to:

* Create or drop databases.
* Create constraints.
* Create indexes.
* Load data.
* Update data.
* Restructure the graph (change graph data model).
* Add users and access control.

=== Examples: Adding constraints

Suppose that we create 3 files to make changes:

*1. AddConstraintsMovies.cypher* that contains the Cypher statements to execute in `cypher-shell`:
----
CREATE CONSTRAINT ON (m:Movie) ASSERT m.title IS UNIQUE;
CREATE CONSTRAINT ON (p:Person) ASSERT p.name IS UNIQUE;
CALL db.constraints();
----
Note that each Cypher statement must end with a `;`.

*2. AddConstraints.sh* that invokes `cypher-shell` using a set of Cypher statements and specifies verbose output:
----
cat /usr/local/work/AddConstraintsMovies.cypher | /usr/bin/cypher-shell -u neo4j -p <InstancePassword>  --database movies --format verbose
----

*3. PrepareDB.sh* that initializes the log file, *PrepareDB.log*, and calls the script to add the constraints:
----
rm -rf /usr/local/work/PrepareDB.log
/usr/local/work/AddConstraints.sh 2>&1 >> /usr/local/work/PrepareDB.log
# Other scripts here
----

When the *PrepareDB.sh* script runs its scripts, all output will be written to the log file, including error output. Then you can simply check the log file to make sure it ran as expected.
Using the Cypher file, together with the run scripts, you can perform something like this to automate changes to a database or set of databases.

[.student-exercise]
== Exercise #8: Scripting changes to the database

//ifndef::backend-htlm5[]
Refer to the *Exercise Guide* for instructions.
//endif::[]

//ifdef::backend-htlm5[]
//include::exercises/Exercise08.adoc
//endif::[]

[.quiz]
== Check your understanding

=== Question 1

What tools do you typically use to automate changes to databases?

Select the correct answers.

[%interactive.answers]
- [x] Terminal shell that you are comfortable with.
- [ ] `neo4j`
- [ ] `neo4j-admin`
- [x] `cypher-shell`

=== Question 2

What tools do you typically use to automate management of databases?

Select the correct answers.

[%interactive.answers]
- [x] Terminal shell that you are comfortable with.
- [ ] `neo4j`
- [x] `neo4j-admin`
- [x] `cypher-shell`

=== Question 3

What type of file would this content be placed in for scripting purposes?

----
CREATE CONSTRAINT ON (d:Department) ASSERT d.num IS UNIQUE;
CREATE CONSTRAINT ON (p:Person) ASSERT p.name IS UNIQUE;
CALL db.constraints();
----

Select the correct answer.

[%interactive.answers]
- [ ] *.txt*
- [ ] *.db*
- [x] *.cypher*
- [ ] *.sh*

== Summary

You should now be able to:

[square]
* Create Cypher scripts to change a database.
* Create shell scripts to execute Cypher scripts.
* Create shell scripts to execute a set of shell scripts.

////
== Grade Quiz and Continue 

++++
<a class="next-section medium button" href="../part-4/">Continue to Module 4</a>
++++

ifdef::backend-html5[]

include::scripts-end.txt[]
++++
<script>
$( document ).ready(function() {
  Intercom('trackEvent','training-admin-view-part3');
});
</script>
++++

endif::backend-html5[]
////
