
= Scripting to Manage Databases
:doctype: book
:toc: left
:toclevels: 3
:prevsecttitle: Changing the Database Location
:prevsect: 7
:currsect: 8
:nextsecttitle: Configuring Plugins
:nextsect: 8
:experimental:
:imagesdir: ../images
:manual: http://neo4j.com/docs/operations-manual/4.0

////
ifdef::backend-html5[]

include::scripts.txt[]

endif::backend-html5[]
////

== About this module

In most cases, you will want to automate the management of a Neo4j instance.

At the end of this module, you should be able to:
[square]
* Create Cypher scripts to change a database.
* Create shell scripts to execute Cypher scripts.
* Create shell scripts to execute a set of shell scripts.

== Scripting with cypher-shell

As a database administrator, you may need to automate changes to databases.
The most common types of changes that administrators may want to perform are related to the application.
As an administrator, you work with architects and developers to created scripts to:

* Create or drop databases
* Create constraints
* Create indexes
* Load data
* Update data
* Restructure the graph (change graph data model)
* Add users and access control.

=== Examples: Adding constraints

Suppose that we create 3 files to make changes:

*1. AddConstraintsMovies.cypher* that contains the Cypher statements to execute in `cypher-shell`:
----
CREATE CONSTRAINT ON (m:Movie) ASSERT m.title IS UNIQUE;
CREATE CONSTRAINT ON (p:Person) ASSERT p.name IS UNIQUE;
CALL db.constraints();
----
Note that each Cypher statement must end with a `;`.

*2. AddConstraints.sh* that invokes `cypher-shell` using a set of Cypher statements and specifies verbose output:
----
cat /usr/local/work/AddConstraintsMovies.cypher | /usr/bin/cypher-shell -u neo4j -p <InstancePassword>  --database movies --format verbose
----

*3. PrepareDB.sh* that initializes the log file, *PrepareDB.log*, and calls the script to add the constraints:
----
rm -rf /usr/local/work/PrepareDB.log
/usr/local/work/AddConstraints.sh 2>&1 >> /usr/local/work/
PrepareDB.log
# Other scripts here
----

When the *PrepareDB.sh* script runs its scripts, all output will be written to the log file, including error output. Then you can simply check the log file to make sure it ran as expected.
Using the Cypher file, together with the run scripts, you can perform something like this to automate changes to a database or set of databases.

[.slide-title.has-gold-background.has-team-background]
==  *Exercise #8: Scripting changes to the database*

//ifndef::backend-htlm5[]
Refer to the *Exercise Guide* for instructions.
//endif::[]

//ifdef::backend-htlm5[]
//include::exercises/Exercise08.adoc
//endif::[]



//[#module-3.quiz]
////
== Check your understanding

=== Question 1

Suppose that you have installed Neo4j Enterprise Edition and have modified the name of the active database in the Neo4j configuration file. What tool and command do you run to create the new database?

Select the correct answer.
[%interactive]
- [ ] [.false-answer]#`neo4j-admin create-database`#
- [ ] [.false-answer]#`neo4j-admin initialize`#
- [ ] [.false-answer]#`neo4j create-database`#
- [ ] [.required-answer]#`neo4j start`#

=== Question 2

Suppose that you want the existing Neo4j database to have the name *ABCRecommendations.db*. Assuming that you have stopped the Neo4j instance, what steps must you perform to modify the name of the database, which currently has a default name of *graph.db*?

Select the correct answers.
[%interactive]
- [ ] [.required-answer]#Rename the *NEO4J_HOME/graph.db* directory to *NEO4J_HOME/ABCRecommendations.db*.#
- [ ] [.required-answer]#Modify *neo4j.conf* to use _dbms.active_database=ABCRecommendations.db_.#
- [ ] [.false-answer]#Run `neo4j-admin rename graph.db ABCRecommendations.db`.#
- [ ] [.false-answer]#Run `neo4j-admin move graph.db ABCRecommendations.db`.#

=== Question 3

How do you copy a database that you want to give to another user?

Select the correct answer.
[%interactive]
- [ ] [.false-answer]#With the Neo4j instance started, run `neo4j-admin copy` providing the location where the copy will be created.#
- [ ] [.false-answer]#With the Neo4j instance stopped, run `neo4j-admin copy` providing the location where the copy will be created.#
- [ ] [.false-answer]#With the Neo4j instance started, run `neo4j-admin dump` providing the location where the dump file will be created.#
- [ ] [.required-answer]#With the Neo4j instance stopped, run `neo4j-admin dump` providing the location where the dump file will be created.#
////
== Summary

You should now be able to:

[square]
* Create Cypher scripts to change a database.
* Create shell scripts to execute Cypher scripts.
* Create shell scripts to execute a set of shell scripts.

////
== Grade Quiz and Continue 

++++
<a class="next-section medium button" href="../part-4/">Continue to Module 4</a>
++++

ifdef::backend-html5[]

include::scripts-end.txt[]
++++
<script>
$( document ).ready(function() {
  Intercom('trackEvent','training-admin-view-part3');
});
</script>
++++

endif::backend-html5[]
////
