= Data Science with Neo4j
:slug: 00-data-science-about
:neo4j-version: 3.4.4
:imagesdir: ../images
:page-slug: {slug}
:page-type: training-course-index
:page-pagination: next
:page-layout: training

== About this course

This course introduces you to using Neo4j as part of your Data Science and Machine Learning workflows.
We're going to learn how to do this with the help of the https://aminer.org/citation[aminer.org citation dataset^].
This dataset contains papers, authors, and citations from DBLP - a computer science bibliography website.

This course is intended for data scientists and data analysts.

This self-paced training should take you three hours to complete if you perform all of the hands-on exercises in the course.

We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance.
You should register on the community site  where you can view other questions and answers for students taking our online training courses.
The _Neo4j Community Site_ is an  excellent resource for answering many types of questions posed by other users of Neo4j.

There are four modules in this course.
Most modules have hands-on exercises you should complete and all modules have a set of review questions at the end.
The hands-on exercises in this course can be completed in a Neo4j Sandbox or in Neo4j Desktop.
We have provided an estimate of how long each module should take you to complete if you perform the hands-on exercises.
