= Photo Based Gallery Recomendations
:slug: 07-gdsaa-photo-based-gallery-recommendations
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-quiz:
:page-module-duration-minutes: 60

video::CJksYzO7zl0[youtube,width=560,height=315]

_Similarity algorithms and Label Propagation overview_

In this section you will use the Label Propagation algorithm to recommend photos.

== Exercise

. In Neo4j Browser, perform the steps in the  Neo4j Browser guide section *Photo Recommendations*. (:play gds-applied-algos-exercises/05.html)
. In React application code, edit the `FETCH_PHOTO_RECOMMENDATIONS` Cypher query in `src/exercises/exercise4.js` to recommend businesses whose photos belong to the same community.
. Save this file.
. In React web application, click *Photos* and select five random photos. Then the application presents restaurants based upon the photos selected.

====
.Useful Resources

* https://neo4j.com/docs/graph-data-science/current/algorithms/label-propagation/[Label Propagation^]
====

[.quiz]
== Check your understanding
=== Question 1

[.statement]
Which category of algorithms best describes LPA?

[.statement]
Select the correct answer.

[%interactive.answers]
- [ ] Centrality
- [ ] Similarity & ML Workflow
- [x] Community Detection
- [ ] Pathfinding and Search

=== Question 2

[.statement]
Which voting mechanism does Neo4j's Label Propagation algorithm use?

[.statement]
Select the correct answer.

[%interactive.answers]
- [ ] Random Walk Method
- [x] Pull Method
- [ ] Push Method
- [ ] Modularity Optimization Method

[.summary]
== Summary

You should now be able to:
[square]
* Use the Jaccard similarity algorithm.
* Use the Label Propagation Community Detection algorithm with Neo4j.
