= Graph Data Modeling for Neo4j: Summary
:slug: 06-graph-data-modeling-summary
:doctype: book
:toc: left
:toclevels: 3
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-certificate:
:page-module-duration-minutes: 5

== Course Summary

In this course, you have learned how to:

[square]
* Describe what a graph data model is for a Neo4j database.
* Design an initial graph data model using Neo4j best practices.
* Describe the core principles used for Neo4j graph data modeling.
* Describe the common structures used in a Neo4j graph data model.
* Refactor and evolve a graph data model.

ifdef::env-slides[]
== Resources - 1
endif::[]

ifndef::env-slides[]
== Resources
endif::[]

There are many resources available to you for learning more about Neo4j and Cypher.

https://neo4j.com/developer/resources/

Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users:

https://community.neo4j.com

Neo4j documentation:

https://neo4j.com/docs/

ifdef::env-slides[]
== Resources - 2
endif::[]

Neo4j Sandboxes for experimenting with graphs:

https://sandbox.neo4j.com/?ref=graph-academy

Videos on  the Neo4j YouTube channel:

https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

Neo4j online and classroom training:

https://neo4j.com/graphacademy/

ifdef::env-slides[]
== Resources - 3
endif::[]

Become a Neo4j certified developer:

https://neo4j.com/graphacademy/neo4j-certification/

[NOTE]
You can take the certification exam multiple times until you pass!

GitHub repository:

https://github.com/neo4j-contrib

Neo4j events all over the world:

https://neo4j.com/events/world/all/

ifdef::env-slides[]
== Resources - 4
endif::[]

Graph Gists for learning more use cases for Neo4j:

https://neo4j.com/graphgists/

Attend a Neo4j meetup:

https://www.meetup.com/topics/neo4j/

View questions/answers raised about Neo4j:

https://stackoverflow.com/tags/neo4j/hot

ifndef::env-slides[]

== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/SzK3ssDRyDG31SL17[feedback] so we can improve this course.
endif::[]
