:imagesdir: ../images

:imagesdir: ../images

== Exercise #5: Copying databases

In this exercise, you will use `neo4j-admin` to copy a database and create a database from a dump file.

=== Before you begin

. Make sure you have a terminal window open to your EC2 instance for this course.
. Ensure that you are the user _neo4j_.
. Ensure that the Neo4j instance is started.

=== Exercise steps

*Part 1*: First you will create a movies database that will be used in this exercise for copying.

. In `cypher-shell` create a database named _movies_.
. Exit out of `cypher-shell`.
. Invoke `cypher-shell` using *movies.cypher* as input and specify _movies_ as the database.
----
/usr/bin/cypher-shell -u neo4j -p <Neo4jInstancePassword> --database movies < /home/ubuntu/files/movies.cypher
----
[start=4]
. In `cypher-shell` confirm that the database was loaded. It should contain 171 nodes:
----
MATCH (n) RETURN count(n);
----

*Part 2*: You will make a copy of the _movies_ database, _movies2_ for local use in the Neo4j instance.

. In `cypher-shell` stop the _movies_ database.
. Exit `cypher-shell`.
. Copy the _movies_ database to the _movies2_ database using the neo4j-admin tool:
----
/usr/bin/neo4j-admin copy --from-database=movies --to-database=movies2
----
[start=4]
. In `cypher-shell' create _movies2_.
. Confirm that this _movies2_ database has 171 nodes.
----
MATCH (n) RETURN count(n);
----

*Part 3*: You will dump the _movies_ database.

. Use the `dump` command of the `neo4j-admin` tool to create the dump file as follows:
----
/usr/bin/neo4j-admin dump --database=movies --to=/home/ubuntu/files/movies.dump
----
[start=2]
. Confirm that the *movies.dump* file was created.

*Part 4*: You use the dump file to create a database.

. Use the `load` command of the `neo4j-admin` tool to create the database, _movies3_ from the dump file as follows:
----
/usr/bin/neo4j-admin load --database=movies3 --from=/home/ubuntu/files/movies.dump
----
[start=2]
. In `cypher-shell' create _movies3_.
. Confirm that this _movies3_ database has 171 nodes.

=== Exercise summary

You have now gained experience copying a database within the Neo4j instance and also creating a dump file that can be used to create a database on a different system.
