:imagesdir: ../images

== *Exercise #9: Install a plugin*


In this Exercise, you will install the APOC library for use by your Neo4j instance and you will create and execute a script to report all of the procedures available to the Neo4j instance.

=== Before you begin

. Make sure you have a terminal window open to your EC2 instance for this course.
. Ensure that you are the user _neo4j_.

=== Exercise steps:

. In a Web browser, go to the GitHub repository for the https://github.com/neo4j-contrib/neo4j-apoc-procedures[APOC library].
. Find the latest release of the library that is compatible with Neo4j Enterprise Edition 4.0.
. Download the already-built *.jar* file into the */var/lib/neo4j/plugins* directory.

----
cd /var/lib/neo4j/plugins
curl -L <URL for the jar file> > <name of the jar file>
----

[start=4]
. Add execute permissions to the file.

----
sudo chmod +x <name of the jar file>
----

[start=5]
. Modify */etc/neo4j/neo4j.conf* to allow (sandbox) all procedures of the APOC library.

----
dbms.security.procedures.unrestricted=apoc.*
----

[start=6]
. Start or restart the Neo4j instance.

[start=7]
. Using `cypher-shell` write a command to create the procedures.txt file that contains all of the procedures that are loaded for the Neo4j instance.

----
echo "CALL dbms.procedures() YIELD name;" | /usr/bin/cypher-shell -u neo4j -p <InstancePassword> --format plain > /home/ubuntu/report/procedures.txt
----

[start=8]
. Confirm that APOC procedures are loaded by examining the file produced.

=== Exercise summary

You have now configured a Neo4j instance so that applications that access the databases can use APOC library procedures.

