
= Setting up your development environment for the training session: Natural Language Processing with Hume
:presenter: Neo Technology
:twitter: neo4j
:doctype: book
:toc: left
:toclevels: 4
:experimental:
:imagesdir: ../images
:manual: http://neo4j.com/docs/developer-manual/current
:manual-cypher: {manual}/cypher

== Preparing for the training session

You must prepare your development environment before you perform the exercises for this training session.

*Step 1:* Download this license file as you will need it for running Hume

https://graphacademy.neo4j.com/setup/hume/hume-api_nodes2020_2020-10-31.lic

[NOTE]
This license file expires October 31, 2020. You can request a new license file by emailing info@graphaware.com.

*Step 2:* Follow the setup instructions here:

https://github.com/graphaware/hume-nodes2020

*Step 3:* Before your start the Docker instance, you will need to configure it to use at least 12-16G of RAM. Please follow these instructions per your system:

* https://docs.docker.com/docker-for-mac/#resources
* https://docs.docker.com/docker-for-windows/#resources

[NOTE]
Because of the size of the configuration, it will take time for processes to start when you begin your hands-on exercises.

Here are the credentials you should use for logging in to Hume:

login : nodes2020

password : XYps4hhLVA9WxHKF


== Getting help

If you have problems with setting up your Neo4j development environment, you can join http://community.neo4j.com/[Neo4j Community] and ask a question https://community.neo4j.com/c/general/online-training[here].

