
= Setting up your development environment for the training session: Master Apache Kafka Streams in Neo4j
:presenter: Neo Technology
:twitter: neo4j
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:manual: http://neo4j.com/docs/developer-manual/current
:manual-cypher: {manual}/cypher

== Preparing for the training session

You must prepare your development environment before you perform the exercises for this training session.

=== Prerequisites

[square]
* At least 16Gb RAM on your system.
* Docker installed (from https://hub.docker.com)

[NOTE]
It will take approximately 1.5 hours to download the files for this training.

=== Steps to prepare your system for the hands-on exercises

. Clone the Github repo:
----
	git clone https://github.com/conker84/neo4j-streams-october-2k20.git
----

[start=2]
. Move into the directory:
----
	cd neo4j-streams-october-2k20
----

[start=3]
. Execute the compose file in order to download all the required images:
----
	docker-compose up -d
----

[start=4]
. Wait until all the images are downloaded, once finished you will see something like this:


----
	Creating elasticsearch ... done
	Creating kibana        ... done
	Creating broker        ... done
	Creating neo4j         ... done
	Creating connect       ... done
	Creating zeppelin      ... done
----

[start=5]
. Once finished, you can shutdown the stack with:
----
	docker-compose down
----

[start=6]
. Wait until everything is down, once finished you will something like this:

----
	Stopping zeppelin      ... done
	Stopping neo4j         ... done
	Stopping connect       ... done
	Stopping broker        ... done
	Stopping kibana        ... done
	Stopping elasticsearch ... done
	Stopping zookeeper     ... done
	Removing zeppelin      ... done
	Removing neo4j         ... done
	Removing connect       ... done
	Removing broker        ... done
	Removing kibana        ... done
	Removing elasticsearch ... done
	Removing zookeeper     ... done
----

[start=7]
. Pull this Docker image separately:

----
	docker pull confluentinc/cp-kafkacat
----

[start=8]
. Before your start the Docker instance, you will need to configure it to use at least 8G of RAM. Please follow these instructions per your system:
.. https://docs.docker.com/docker-for-mac/#resources
.. https://docs.docker.com/docker-for-windows/#resources

[NOTE]
Because of the size of the configuration, it will take time for processes to start when you begin your hands-on exercises.

== Getting help

If you have problems with setting up your Neo4j development environment, you can join http://community.neo4j.com/[Neo4j Community] and ask a question https://community.neo4j.com/c/general/online-training[here].

