= Cypher Query Tuning with Neo4j 4.0
:slug: 00-cqt-40-about
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:module-next-title: How Queries Work in Neo4j
:page-slug: {slug}
:page-type: training-course-index
:page-pagination: next
:page-layout: training

== About this course

This course teaches you how queries work in Neo4j, how you can analyze them and make your queries perform better.

[.notes]
--
This course is intended for developers who will be implementing the Cypher code to support the queries of an application.
It is expected that you have programming experience in Cypher.
This course does not cover optimizing Cypher statements for modifying the graph, only retrieving data from the graph.
--

In this course, you complete hands-on exercises to analyze and improve queries.
You can complete the hands-on exercises using:

[square]
[.statement]
* Neo4j Desktop
* Neo4j Aura

ifdef::backend-html5[]
At the end of each lesson are a set of questions that you must answer correctly to mark the lesson as completed.
If you complete all lessons, you will receive a _Certificate of Completion_.

If you perform the hands-on exercises, this course will take you approximately 4 hours to complete.
endif::[]


This Course is published by Neo4j per this https://neo4j.com/docs/license/[License for Use^].

== Lesson Overview

Here are the lessons of this course:

. How Queries Work in Neo4j
. Preparing for Query Tuning
. Reducing Cardinality
. Optimizing Property Access
. Monitoring Queries

== Resources

ifndef::env-slides[]
We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance.
You should register on the community site where you can view other questions and answers for students taking our online training courses.
The Neo4j Community Site is an excellent resource for answering many types of questions posed by other users of Neo4j.
endif::[]

Here are some resources you will use as you learn about Neo4j and Cypher for this course:

[square]
* https://neo4j.com/docs/cypher-manual/4.0/[Neo4j Cypher Manual]
* https://neo4j.com/docs/cypher-refcard/current/[Neo4j Cypher Refcard]
* https://neo4j.com/developer/kb/[Cypher Knowledge Base]
* https://neo4j.com/docs/labs/apoc/current/[APOC Documentation]
ifndef::env-slides[]
* https://community.neo4j.com/c/general/online-training[Neo4j Community Site]
endif::[]
