= Analysis of commonly used together ingredients
:slug: 10-iga-40-ingredient-analysis
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:module-next-title: Memory Requirements Estimation


== Analysis of commonly used together ingredients (Overview)

We have learned the graph workflow in the GDS library and how to use various graph algorithms.
Now we will put our knowledge together and create a sample analysis.
We will try to find communities of commonly used together ingredients and find their representatives.
This is quite a common graph workflow.

== Analysis of commonly used together ingredients (Algorithms)

We will first infer a similarity network between ingredients with the help of the Node Similarity algorithm.
The algorithm is frequently used to infer a monopartite graph from an input bipartite graph.
Instead of writing back the results, we will use the *mutate* mode of the Node Similarity algorithm.
In the next step we will try to find communities of commonly used together ingredients with the help of the Louvain algorithm.
For the final step, we will search of representatives of those communities with the help of the PageRank algorithm.
If every link means that the ingredients are commonly used together, the PageRank will return ingredients that are commonly used together with other ingredients that are also commonly used together.
This can be understood as the representatives of the communities.

This is a common workflow where we use the results of the previous algorithm as an input for the next one.
So we will use the results of the Node Similarity algorithm to find communities within the inferred network.
Then we will take the results of the community detection algorithm and search for representatives within those communities with the PageRank algorithm.

== Analysis of commonly used together ingredients: Exercise

In Neo4j Browser:
* :play intro-graph-algos-exercises  (Ingredient analysis)

== Summary
