= Practical Application of Algorithms
:slug: 10-iga-40-ingredient-analysis
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:module-next-title: Additional Information


== Practical application of algorithms overview

Now that you have familiarized yourself with graph algorithms and how to execute them in the Graph Data Science library, you will do a quick graph analysis of the Recipes dataset.
The goal is to find communities of commonly used together ingredients and the representatives of those communities.

== Practical application of algorithms workflow

The analysis consists of three steps.
First, you will infer a similarity network between ingredients with the help of the Node Similarity algorithm.
The algorithm will compare how often the ingredients are used together in the same recipe.
As in the previous lesson, you will start by examining the Jaccard Similarity score distribution to help you define reasonable *topK* and *similarityCutoff* parameters.
This way, the inferred network between ingredients will not be too sparse or too dense.

Next, you will use the Louvain Modularity algorithm to analyze the community structure of the ingredient similarity network.
You will investigate how the *topK* and *similarityCutoff* parameters of the Node Similarity algorithm directly influence the size and the structure of communities.

Finally, you will use the PageRank algorithm to find the representatives of those communities.
When using the PageRank algorithm, think of every relationship as a vote of confidence or influence. In our analysis, every relationship is a vote of commonly used together ingredients, and so the most frequently used together ingredients will rank the highest. You could think of them as the representatives of those communities.

[.student-exercise]
== Exercise: Practical application of algorithms

In Neo4j Browser: kbd:[:play 4.0-intro-graph-algos-exercises] and follow the instructions for *Practical application*.

[.quiz]
== Check your understanding

=== Question 1

[.statement]
Given the recipe dataset, what algorithm do you use to determine how often the ingredients are used together in the same recipe.

[.statement]
Select the correct answer.

[%interactive.answers]
- [ ] Weakly Connected Components
- [ ] Local Clustering Coefficient
- [ ] Louvain Modularity
- [x] Node Similarity

=== Question 2

[.statement]
The second part of the analysis is to determine the community structure of the nodes that have been found to be similar.
What algorithm is used to determine this community structure?

[.statement]
Select the correct answers.

[%interactive.answers]
- [x] Louvain Modularity
- [ ] Label Propagation
- [ ] Weakly Connected Components
- [ ] Local Clustering Coefficient

=== Question 3

[.statement]
Once the communities have been identified, what algorithm to you use to deterimine the most frequently-used together ingredients.

[.statement]
Select the correct answer.

[%interactive.answers]
- [ ] Label Propagation
- [x] PageRank
- [ ] Local Clustering Coefficient
- [ ] Louvain Modularity

[.summary]
== Summary

In this lesson, you performed an analysis using the Graph Data Science Library algorithms.
