= Summary
:slug: 12-iga-40-summary
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images

== Summary

You should now be able to:

[square]
* Describe how Neo4j supports graph algorithms for analysis and machine learning.
* Describe the components of the Neo4j Graph Data Science library.
* Set up your environment for running graph algorithms.
* Describe the workflow you use to use the Graph Data Science library.
* Determine memory requirements for your analysis.
* Use Community Detection algorithms.
* Use Centrality algorithms.
* Use Similarity algorithms.
* Perform data analysis using a set of graph algorithms.
* Describe some best practices for using algorithms.

ifndef::env-slides[]
== Resources
endif::[]

ifdef::env-slides[]
== Resources - 1
endif::[]


There are many resources available to you for learning more about Neo4j and Cypher.

https://neo4j.com/developer/resources/

Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users:

https://community.neo4j.com

Neo4j documentation:

https://neo4j.com/docs/

ifdef::env-slides[]
== Resources - 2
endif::[]

Neo4j Sandboxes for experimenting with graphs:

https://sandbox.neo4j.com/?ref=graph-academy

Videos on  the Neo4j YouTube channel:

https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

Neo4j online and classroom training:

https://neo4j.com/graphacademy/

ifdef::env-slides[]
== Resources - 3
endif::[]

Become a Neo4j certified developer:

https://neo4j.com/graphacademy/neo4j-certification/

GitHub repository:

https://github.com/neo4j-contrib

Neo4j events all over the world:

https://neo4j.com/events/world/all/

ifdef::env-slides[]
== Resources - 4
endif::[]

Graph Gists for learning more use cases for Neo4j:

https://neo4j.com/graphgists/

Attend a Neo4j meetup:

https://www.meetup.com/topics/neo4j/

View questions/answers raised about Neo4j:

https://stackoverflow.com/tags/neo4j/hot

ifndef::env-slides[]
== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/EsBJcFPFi3k48H2i8[feedback] so we can improve this course.
endif::[]

ifdef::backend-html5[]
[.certificate]
== Certificate
endif::[]
