= Basic Neo4j 4.0 Administration: Summary
:slug: 13-basic-neo4j-admin-summary
:doctype: book
:toc: left
:toclevels: 3
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-certificate:

== Course Summary

In this course, you have learned how to:

[square]
* Manage Neo4j instances.
* Use cypher-shell to access the instances.
* Copy, back up, and change the location of the databases.
* Check the consistency of a database.
* Create scripts to manage databases.
* Configure HTTP ports and plugins.
* Import data into Neo4j.

ifdef::env-slides[]
== Resources - 1
endif::[]

ifndef::env-slides[]
== Resources
endif::[]

There are many resources available to you for learning more about Neo4j.

Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users:

https://community.neo4j.com

Neo4j documentation:

https://neo4j.com/docs/

ifdef::env-slides[]
== Resources - 2
endif::[]

Videos on  the Neo4j YouTube channel:

https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

Neo4j online and classroom training:

https://neo4j.com/graphacademy/

ifdef::env-slides[]
== Resources - 3
endif::[]

GitHub repository:

https://github.com/neo4j-contrib

Neo4j events all over the world:

https://neo4j.com/events/world/all/

ifdef::env-slides[]
== Resources - 4
endif::[]

Graph Gists for learning more use cases for Neo4j:

https://neo4j.com/graphgists/

Attend a Neo4j meetup:

https://www.meetup.com/topics/neo4j/

View questions/answers raised about Neo4j:

https://stackoverflow.com/tags/neo4j/hot

ifndef::env-slides[]
== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/2oJfsxgUEwjUiv2i9[feedback] so we can improve this course.
endif::[]
