= Memory Requirements Estimation
:slug: 06-iga-40-memory-requirements-estimation
:doctype: book
:toc: left
:toclevels: 4
:imagesdir: ../images
:page-slug: {slug}
:page-layout: training
:page-quiz:
:page-module-duration-minutes: 10

== Memory Requirements estimation

[.notes]
--
The Graph Data Science library operates entirely on heap memory.
To avoid running out of memory when dealing with large networks, you can estimate the required memory before executing the algorithms.
GDSL supports estimating the required memory to load a named graph as well as to execute a graph algorithm by using the _estimate_ mode.

The general syntax is as follows:
--

[source,syntax,role=nocopy noplay]
----
CALL gds.<ALGO>.<MODE>.estimate()
----

[.notes]
--
All algorithm procedures in the GDSL, including graph creation, will do an estimation check at the beginning of their execution.
If the estimation check determines that the current amount of free memory is insufficient to complete the operation, the operation will be aborted, and an error will be reported. 
This heap control logic is restrictive in the sense that it only blocks executions that are certain to not fit into memory. It does not guarantee that an execution that passed the heap control will succeed without depleting memory. Thus, it is still useful to first run the estimation mode before running an algorithm or graph creation on a large data set to ensure you will not run out of memory.
--

The amount of free heap memory can be increased by either dropping unused named graphs from the Graph Catalog, or increasing the maximum heap size before starting the Neo4j instance.

[.student-exercise]
== Exercise: Memory requirements estimation

In Neo4j Browser: kbd:[:play 4.0-intro-graph-algos-exercises] and follow the instructions for *Memory requirements*.

[NOTE]
Estimated time to complete: 5 minutes

[.quiz]
== Check your understanding

=== Question 1

[.statement]
What algorithms can you estimate heap memory for?

[.statement]
Select the correct answers.

[%interactive.answers]
- [x] Betweenness Centrality
- [ ] Closeness Centrality
- [x] PageRank
- [x] Label Propagation

=== Question 2

[.statement]
When calling estimate() to provide the heap memory estimation for running the algorithm, what information must you provide?

[.statement]
Select the correct answers.

[%interactive.answers]
- [x] name of the algorithm
- [x] mode of the algorithm (stream, write)
- [ ] amount of heap configured for the instance
- [ ] size of the graph

=== Question 3

[.statement]
What factors impact the amount of memory available for an algorithm?

[.statement]
Select the correct answers.

[%interactive.answers]
- [x] the size of the projected graph
- [x] the amount of heap available to the instance
- [ ] the number of previously executed algorithms
- [x] the particular algorithm that will run

[.summary]
== Summary

In this lesson you learned how to estimate the memory requirements for you graph algorithm analysis.
