= Neo4j Training Material: Publish pages
:uri-wp-rest-api-ref: https://developer.wordpress.org/rest-api/reference/

== Publish to WordPress

The infrastructure is consisting of:

Amazon S3::
Used to host static resources (mostly images). +
Two buckets are available:

- testing
- production

WordPress::
A single WordPress instance for both private and public pages.

Backend API::
Used to manage quizzes answers and certificates and hosted on AWS Labmda. +
Two instances are available:

- testing
- production

=== Stages

We are using 3 stages:

- `local`
- `testing`
- `production`

You can define the stage using the property "stage" in the Gradle command line:

 $ ./gradlew 4.0-intro-neo4j:convertOnlineHtml -Pstage=local

==== Local stage

We are using this stage to preview local HTML content before publishing to WordPress.
The HTML produced will be almost identical to what will be published to WordPress but the page won't use the exact same style and features.
In other words, the page might look different on WordPress compared to what you are seeing on local preview.
We are mostly using this stage to make sure that the content is well formatted.

==== Testing stage

In testing stage, we will publish _private_ pages to WordPress.
Private pages can only be seen if you're logged in to your WordPress account.
In other words, private pages, cannot be seen by unauthenticated users.

In testing stage, we will use the "testing" S3 bucket and the "testing" backend API instance to not make sure that we are not impacting the production pages.

In addition, pages will be published using a prefixed slug.
For instance, if your page slug is: `01-neo4j-graph-database`,
then the page will be effectively published on WordPress using the slug `+_testing_01-neo4j-graph-database+`.
Otherwise, the live page will be overwritten since we are using a single WordPress instance.

==== Production stage

Publish _public_ pages to WordPress using the "production" S3 bucket and the "production" backend API instance.

=== Prerequisite

To publish pages to WordPress, you will need an application account to authenticate with the {uri-wp-rest-api-ref}[WordPress REST API].
You will also need an S3 account to push images to S3.

==== Upload images to S3

The following command will upload the images of the _4.0-intro-neo4j_ module to S3 using the AWS profile named _neo4j_:

 $ ./gradlew :4.0-intro-neo4j:s3UploadImages -Ps3-profile=neo4j

This process only adds or updates (if the `overwrite` attribute is set to true) images.
In other words, this process won't remove images from S3.

==== AsciiDoc attribute

A page must have a (unique) `slug` attribute:

[source,adoc]
----
= Introduction to Cypher
:slug: introduction-cypher
----



=== Upload to WordPress

The following command will publish pages to WordPress:

 $ ./gradlew 4.0-intro-neo4j:wordPressUploadCourse -Pwordpress-username=neo -Pwordpress-host="neo4j.com" -Pwordpress-password="abcd"

If the slug already exists, the page will be updated. Otherwise the page will be created.
This process won't remove pages from WordPress.

=== How?

A companion YAML file will be produced for each page during the build:

[source]
----
00_AboutThisCourse.html
00_AboutThisCourse.yml
----

.00_AboutThisCourse.yml
[source,yaml]
----
slug: "introduction-to-neo4j-4-0"
title: "Introduction to Neo4j 4.0"
----

This file will be used by the WordPress plugin to update the HTML content of the corresponding page (using the slug).

In addition, a module descriptor will also be generated:

.asciidoctor-module-descriptor.yml
[source,yaml]
----
nav:
- title: "Introduction to Neo4j 4.0"
  url: "00_AboutThisCourse.html"
  slug: "introduction-to-neo4j-4-0"

- title: "Neo4j is a Graph Database"
  url: "01_Neo4jIsAGraphDatabase.html"
  slug: "neo4j-graph-database"

- title: "The Neo4j Graph Platform"
  url: "02_TheNeo4jGraphPlatform.html"
  slug: "neo4j-graph-platform"
----

The above file will be used to generate the Table Of Contents. In the future, we might use this file to add the next/previous page:

[source,yaml]
----
nav:
- title: "Introduction to Neo4j 4.0"
  url: "00_AboutThisCourse.html"
  slug: "introduction-to-neo4j-4-0"
  next:
    slug: "neo4j-graph-database"

- title: "Neo4j is a Graph Database"
  url: "01_Neo4jIsAGraphDatabase.html"
  slug: "neo4j-graph-database"
  previous:
    slug: "introduction-to-neo4j-4-0"
  next:
    slug: "neo4j-graph-platform"

- title: "The Neo4j Graph Platform"
  url: "02_TheNeo4jGraphPlatform.html"
  slug: "neo4j-graph-platform"
  previous:
    slug: "neo4j-graph-database"
----
